name: dim8
channels:
  - pytorch
  - nvidia/label/cuda-11.7.0
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - accelerate=0.28.0=pyhd8ed1ab_0
  - aiohttp=3.9.3=py310h2372a71_1
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - aws-c-auth=0.7.16=haed3651_8
  - aws-c-cal=0.6.10=ha9bf9b1_2
  - aws-c-common=0.9.14=hd590300_0
  - aws-c-compression=0.2.18=h4466546_2
  - aws-c-event-stream=0.4.2=he635cd5_6
  - aws-c-http=0.8.1=hbfc29b2_7
  - aws-c-io=0.14.6=h6b388c4_1
  - aws-c-mqtt=0.10.3=hffff1cc_2
  - aws-c-s3=0.5.3=h4893938_0
  - aws-c-sdkutils=0.1.15=h4466546_2
  - aws-checksums=0.1.18=h4466546_2
  - aws-crt-cpp=0.26.4=h335f1a1_1
  - aws-sdk-cpp=1.11.267=hb1af6a8_4
  - babel=2.14.0=pyhd8ed1ab_0
  - beartype=0.17.2=pyhd8ed1ab_0
  - bitarray=2.9.2=py310h2372a71_0
  - bitsandbytes=0.43.0=py310h8f3e6f0_0
  - blas=2.120=mkl
  - blas-devel=3.9.0=20_linux64_mkl
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.1.0=py310hc6cd4ac_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.27.0=hd590300_0
  - ca-certificates=2024.6.2=hbcca054_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - cloudpickle=3.0.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.2.1=py310hd41b1e2_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvcc=11.7.64=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cudatoolkit=11.7.0=hd8887f6_10
  - cycler=0.12.1=pyhd8ed1ab_0
  - cytoolz=0.12.3=py310h2372a71_0
  - dask-core=2024.5.1=pyhd8ed1ab_0
  - datasets=2.18.0=pyhd8ed1ab_0
  - diffusers=0.27.1=pyhd8ed1ab_0
  - dill=0.3.8=pyhd8ed1ab_0
  - einops=0.7.0=pyhd8ed1ab_1
  - fairseq=0.12.3=py310h3267e3a_3
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=pyhd8ed1ab_0
  - fonttools=4.52.1=py310hc51659f_0
  - freetype=2.12.1=h267a509_2
  - frozenlist=1.4.1=py310h2372a71_0
  - fsspec=2024.2.0=pyhca7485f_0
  - gflags=2.2.2=he1b5a44_1004
  - ghp-import=2.1.0=pyhd8ed1ab_0
  - glog=0.7.0=hed5481d_0
  - gmp=6.3.0=h59595ed_1
  - gmpy2=2.1.2=py310h3ec546c_1
  - gnutls=3.6.13=h85f3911_1
  - huggingface_hub=0.21.4=pyhd8ed1ab_0
  - hydra-core=1.3.2=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.6=pyhd8ed1ab_0
  - imagecodecs-lite=2019.12.3=py310h261611a_8
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py310hd41b1e2_1
  - krb5=1.21.2=h659d440_0
  - lame=3.100=h166bdaf_1003
  - lazy_loader=0.4=pyhd8ed1ab_0
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240116.1=cxx17_h59595ed_2
  - libarrow=15.0.2=hb86450c_1_cpu
  - libarrow-acero=15.0.2=h59595ed_1_cpu
  - libarrow-dataset=15.0.2=h59595ed_1_cpu
  - libarrow-flight=15.0.2=hc6145d9_1_cpu
  - libarrow-flight-sql=15.0.2=h757c851_1_cpu
  - libarrow-gandiva=15.0.2=hb016d2e_1_cpu
  - libarrow-substrait=15.0.2=h757c851_1_cpu
  - libblas=3.9.0=20_linux64_mkl
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=20_linux64_mkl
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.9.0.20=0
  - libcurand=10.3.5.119=0
  - libcurl=8.6.0=hca28451_0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.17=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_5
  - libgfortran-ng=13.2.0=h69a702a_5
  - libgfortran5=13.2.0=ha4646dd_5
  - libgomp=13.2.0=h807b86a_5
  - libgoogle-cloud=2.22.0=h9be4e54_1
  - libgoogle-cloud-storage=2.22.0=hc7a4891_1
  - libgrpc=1.62.1=h15f2491_0
  - libhwloc=2.9.3=default_h554bfaf_1009
  - libiconv=1.17=hd590300_2
  - liblapack=3.9.0=20_linux64_mkl
  - liblapacke=3.9.0=20_linux64_mkl
  - libllvm16=16.0.6=hb3ce162_3
  - libnghttp2=1.58.0=h47da74e_1
  - libnl=3.9.0=hd590300_0
  - libnpp=11.7.4.75=0
  - libnsl=2.0.1=hd590300_0
  - libnvjpeg=11.8.0.2=0
  - libparquet=15.0.2=h352af49_1_cpu
  - libpng=1.6.43=h2797004_0
  - libprotobuf=4.25.3=h08a7969_0
  - libre2-11=2023.09.01=h5a48ba9_2
  - libsentencepiece=0.2.0=hb0b37bd_1
  - libsqlite=3.45.2=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libthrift=0.19.0=hb90f79a_1
  - libtiff=4.5.0=h6adf6a1_2
  - libutf8proc=2.8.0=h166bdaf_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.13=h7f98852_1004
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.6=h232c23b_0
  - libxslt=1.1.39=h76b75d6_0
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=18.1.2=h4dfa4b3_0
  - locket=1.0.0=pyhd8ed1ab_0
  - loguru=0.7.2=py310hff52083_1
  - lxml=5.1.0=py310hcfd0673_0
  - lz4-c=1.9.4=hcb278e6_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.5=py310h2372a71_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - mergedeep=1.3.4=pyhd8ed1ab_0
  - mkdocs-material-extensions=1.3.1=pyhd8ed1ab_0
  - mkl=2023.2.0=h84fe81f_50496
  - mkl-devel=2023.2.0=ha770c72_50496
  - mkl-include=2023.2.0=h84fe81f_50496
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.1=h9458935_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - multidict=6.0.5=py310h2372a71_0
  - multiprocess=0.70.16=py310h2372a71_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.4.20240210=h59595ed_0
  - nettle=3.6=he412f7d_0
  - networkx=3.2.1=pyhd8ed1ab_0
  - numexpr=2.9.0=mkl_py310hc8c826e_0
  - numpy=1.26.4=py310hb13e2d6_0
  - omegaconf=2.3.0=pyhd8ed1ab_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.3.0=h4ab18f5_3
  - orc=2.0.0=h1e5e2c1_0
  - packaging=24.0=pyhd8ed1ab_0
  - paginate=0.5.6=pyhd8ed1ab_0
  - pandas=2.2.1=py310hcc13569_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pathspec=0.12.1=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pillow=9.4.0=py310h023d228_1
  - pip=24.0=pyhd8ed1ab_0
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - portalocker=2.8.2=py310hff52083_1
  - proplot=0.9.7=pyhd8ed1ab_0
  - psutil=5.9.8=py310h2372a71_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyarrow=15.0.2=py310hf9e7431_1_cpu
  - pyarrow-hotfix=0.6=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.13=hd12c33a_1_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python-xxhash=3.4.1=py310h2372a71_0
  - python_abi=3.10=4_cp310
  - pytorch=2.0.1=py3.10_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=pyhd8ed1ab_0
  - pywavelets=1.4.1=py310h1f7b6fc_1
  - pyyaml=6.0.1=py310h2372a71_1
  - pyyaml-env-tag=0.1=pyhd8ed1ab_0
  - rdma-core=50.0=hd3aeb46_1
  - re2=2023.09.01=h7f4b329_2
  - readline=8.2=h8228510_1
  - regex=2023.12.25=py310h2372a71_0
  - requests=2.31.0=pyhd8ed1ab_0
  - rich=13.7.1=pyhd8ed1ab_0
  - s2n=1.4.7=h06160fa_0
  - sacrebleu=2.4.1=pyhd8ed1ab_0
  - safetensors=0.4.2=py310hcb5633a_0
  - scikit-image=0.20.0=py310h9b08913_1
  - scipy=1.12.0=py310hb13e2d6_2
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - sentencepiece=0.2.0=hff52083_1
  - sentencepiece-python=0.2.0=py310h89c1fb0_1
  - sentencepiece-spm=0.2.0=hb0b37bd_1
  - setuptools=69.2.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=h9fff704_0
  - statsmodels=0.14.2=py310h261611a_0
  - sympy=1.12=pypyh9d50eac_103
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tbb=2021.11.0=h00ab1b0_1
  - tifffile=2020.6.3=py_0
  - tiktoken=0.6.0=py310h47bb294_0
  - timm=0.9.16=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tokenizers=0.15.2=py310h320607d_0
  - toolz=0.12.1=pyhd8ed1ab_0
  - torchaudio=2.0.2=py310_cu117
  - torchdiffeq=0.2.2=pyhd8ed1ab_0
  - torchtriton=2.0.0=py310
  - torchvision=0.15.2=py310_cu117
  - tornado=6.4=py310h2372a71_0
  - tqdm=4.66.2=pyhd8ed1ab_0
  - transformers=4.39.1=pyhd8ed1ab_0
  - typing-extensions=4.10.0=hd8ed1ab_0
  - typing_extensions=4.10.0=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - ucx=1.15.0=h11edf95_7
  - unicodedata2=15.1.0=py310h2372a71_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - watchdog=4.0.0=py310hff52083_0
  - wheel=0.43.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xxhash=0.8.2=hd590300_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.9.4=py310h2372a71_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  - pip:
      - alabaster==0.7.16
      - appdirs==1.4.4
      - argparse==1.4.0
      - automat==22.10.0
      - av==12.0.0
      - beautifulsoup4==4.12.3
      - biokit==0.5.0
      - biopython==1.83
      - bioservices==1.11.2
      - blessed==1.20.0
      - buildtools==1.0.6
      - cachetools==5.3.3
      - cattrs==23.2.3
      - causal-conv1d==1.1.3
      - cffi==1.16.0
      - cmake==3.29.3
      - colorlog==6.8.2
      - colormap==1.1.0
      - colt5-attention==0.10.20
      - constantly==23.10.4
      - cryptography==42.0.5
      - decorator==4.4.2
      - decord==0.6.0
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - docutils==0.21.2
      - easydev==0.13.2
      - einops-exts==0.0.4
      - einx==0.1.3
      - exceptiongroup==1.2.0
      - flake8==7.0.0
      - frozendict==2.4.0
      - ftfy==6.2.0
      - furl==2.1.3
      - gevent==24.2.1
      - gitdb==4.0.11
      - gitpython==3.1.42
      - gpustat==1.1.1
      - greenlet==3.0.3
      - grequests==0.7.0
      - htmlmin==0.1.12
      - hyperlink==21.0.0
      - imageio==2.34.0
      - imageio-ffmpeg==0.4.9
      - imagesize==1.4.1
      - incremental==22.10.0
      - iniconfig==2.0.0
      - jsmin==3.0.1
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - libcst==1.1.0
      - lightning-utilities==0.11.2
      - line-profiler==4.1.3
      - lion-pytorch==0.1.2
      - lit==18.1.6
      - livereload==2.6.3
      - llvmlite==0.42.0
      - local-attention==1.9.0
      - mamba-ssm==1.1.1
      - markdown==3.1.1
      - markdown-katex==201912.11b0
      - matplotlib==3.9.0
      - mccabe==0.7.0
      - mkdocs==1.0.4
      - mkdocs-material==4.6.0
      - mkdocs-minify-plugin==0.2.1
      - moviepy==1.0.3
      - mypy-extensions==1.0.0
      - ninja==1.11.1.1
      - numba==0.59.1
      - numpydoc==1.7.0
      - nvidia-ml-py==12.535.133
      - open-clip-torch==2.24.0
      - opencv-python==4.10.0.82
      - orderedmultidict==1.0.1
      - pathlib2==2.3.7.post1
      - pendulum==3.0.0
      - pep562==1.1
      - pexpect==4.9.0
      - pluggy==1.4.0
      - prettytable==3.10.0
      - proglog==0.1.10
      - protobuf==4.25.3
      - ptyprocess==0.7.0
      - pulp==2.8.0
      - pycodestyle==2.11.1
      - pycparser==2.21
      - pyflakes==3.2.0
      - pymdown-extensions==6.2.1
      - pytest==8.1.1
      - python-dotenv==1.0.1
      - redo==2.0.4
      - referencing==0.34.0
      - requests-cache==1.2.0
      - rpds-py==0.18.0
      - self-attention-cv==1.2.3
      - sentry-sdk==1.43.0
      - setproctitle==1.3.3
      - setuptools-scm==8.1.0
      - simplejson==3.19.2
      - skypilot==0.5.0
      - smmap==5.0.1
      - snowballstemmer==2.2.0
      - soupsieve==2.5
      - sphinx==7.3.7
      - sphinxcontrib-applehelp==1.0.8
      - sphinxcontrib-devhelp==1.0.6
      - sphinxcontrib-htmlhelp==2.0.5
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.7
      - sphinxcontrib-serializinghtml==1.1.10
      - sqlalchemy==2.0.30
      - suds-community==1.1.2
      - thop==0.1.1-2209072238
      - time-machine==2.14.1
      - tokenmonster==1.1.12
      - tomli==2.0.1
      - torchfix==0.4.0
      - torchmetrics==1.3.2
      - twisted==24.3.0
      - typing==3.7.4.3
      - typing-inspect==0.9.0
      - url-normalize==1.4.3
      - vector-quantize-pytorch==1.14.1
      - wandb==0.16.4
      - wcwidth==0.2.13
      - wrapt==1.16.0
      - xmltodict==0.13.0
      - zetascale==2.2.6
      - zope-event==5.0
      - zope-interface==6.4.post2
prefix: /opt/conda/envs/dim8
