name: DiffMa
channels:
  - nvidia
  - nvidia/label/cuda-11.7.0
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2024.6.2=hbcca054_0
  - cuda-nvcc=11.7.64=0
  - cudatoolkit=11.7.0=hd8887f6_10
  - ld_impl_linux-64=2.40=hf3520f5_7
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h77fa898_10
  - libgomp=13.2.0=h77fa898_10
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libstdcxx-ng=13.2.0=hc0a3c3a_10
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.3.1=h4ab18f5_1
  - ncurses=6.5=h59595ed_0
  - openssl=3.3.1=h4ab18f5_0
  - packaging=24.1=pyhd8ed1ab_0
  - pip=24.0=pyhd8ed1ab_0
  - python=3.10.0=h543edf9_3_cpython
  - readline=8.2=h8228510_1
  - setuptools=70.0.0=pyhd8ed1ab_0
  - sqlite=3.46.0=h6d4b2fc_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.43.0=pyhd8ed1ab_1
  - xz=5.2.6=h166bdaf_0
  - pip:
      - accelerate==0.31.0
      - antlr4-python3-runtime==4.9.3
      - causal-conv1d==1.2.2.post1
      - certifi==2022.12.7
      - chardet==5.2.0
      - charset-normalizer==2.1.1
      - click==8.1.7
      - cloudpickle==3.0.0
      - cmake==3.25.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - decord==0.6.0
      - diffusers==0.29.0
      - docker-pycreds==0.4.0
      - einops==0.8.0
      - exceptiongroup==1.2.1
      - filelock==3.13.1
      - fonttools==4.53.0
      - fsspec==2024.6.0
      - ftfy==6.2.0
      - fvcore==0.1.5.post20221221
      - gitdb==4.0.11
      - gitpython==3.1.43
      - huggingface-hub==0.23.4
      - idna==3.4
      - importlib-metadata==7.1.0
      - iniconfig==2.0.0
      - iopath==0.1.10
      - jinja2==3.1.3
      - kiwisolver==1.4.5
      - lightning-utilities==0.11.2
      - lit==15.0.7
      - loguru==0.7.2
      - mamba-ssm==2.0.4
      - markupsafe==2.1.5
      - matplotlib==3.9.0
      - mpmath==1.3.0
      - networkx==3.2.1
      - ninja==1.11.1.1
      - numpy==1.26.3
      - omegaconf==2.3.0
      - open-clip-torch==2.24.0
      - pandas==2.2.2
      - pillow==10.2.0
      - platformdirs==4.2.2
      - pluggy==1.5.0
      - portalocker==2.8.2
      - protobuf==5.27.1
      - psutil==5.9.8
      - pyparsing==3.1.2
      - pytest==8.2.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - regex==2024.5.15
      - requests==2.28.1
      - safetensors==0.4.3
      - seaborn==0.13.2
      - sentencepiece==0.2.0
      - sentry-sdk==2.5.1
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - submitit==1.5.1
      - sympy==1.12
      - tabulate==0.9.0
      - tensorboardx==2.6.2.2
      - termcolor==2.4.0
      - timm==1.0.3
      - tokenizers==0.19.1
      - tomli==2.0.1
      - torch==2.0.0+cu117
      - torchaudio==2.0.0+cu117
      - torchmetrics==1.4.0.post0
      - torchvision==0.15.0+cu117
      - tqdm==4.66.4
      - transformers==4.41.2
      - triton==2.3.1
      - typing-extensions==4.9.0
      - tzdata==2024.1
      - urllib3==1.26.13
      - wandb==0.17.2
      - wcwidth==0.2.13
      - yacs==0.1.8
      - zipp==3.19.2
prefix: /opt/conda/envs/DiffMa
